In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten


In [2]:
from tensorflow.keras.layers import Embedding

In [3]:
# define documents
docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work',
        'Could have done better.']

In [4]:
# 1 = Positive Sentiment
# 0 = Negative Sentiment

In [5]:
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [6]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]

In [7]:
print(encoded_docs)

[[31, 26], [41, 37], [27, 44], [33, 37], [39], [12], [24, 44], [38, 41], [24, 37], [11, 46, 26, 29]]


In [8]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

In [9]:
print(padded_docs)

[[31 26  0  0]
 [41 37  0  0]
 [27 44  0  0]
 [33 37  0  0]
 [39  0  0  0]
 [12  0  0  0]
 [24 44  0  0]
 [38 41  0  0]
 [24 37  0  0]
 [11 46 26 29]]


In [10]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [12]:
# summarize the model
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [13]:
import numpy as np

In [14]:
padded_docs = np.array(padded_docs)
padded_docs

array([[31, 26,  0,  0],
       [41, 37,  0,  0],
       [27, 44,  0,  0],
       [33, 37,  0,  0],
       [39,  0,  0,  0],
       [12,  0,  0,  0],
       [24, 44,  0,  0],
       [38, 41,  0,  0],
       [24, 37,  0,  0],
       [11, 46, 26, 29]])

In [15]:
labels = np.array(labels)
labels

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [16]:
# fit the model
history = model.fit(padded_docs, labels, epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 0s/step - loss: 0.6933 - acc: 0.5000
Epoch 2/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6920 - acc: 0.5000
Epoch 3/50
1/1 [==============================] - 0s 1000us/step - loss: 0.6906 - acc: 0.5000
Epoch 4/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6893 - acc: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6879 - acc: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6866 - acc: 0.7000
Epoch 7/50
1/1 [==============================] - 0s 1000us/step - loss: 0.6853 - acc: 0.8000
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6839 - acc: 0.8000
Epoch 9/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6826 - acc: 0.8000
Epoch 10/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6812 - acc: 0.8000
Epoch 11/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6799 - acc:

In [17]:
history.history.keys()

dict_keys(['loss', 'acc'])

In [18]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 89.999998


In [19]:
# Predict new document sentiment

In [20]:
doc_test = ['Great nice']



In [21]:
encoded_doc_test = [one_hot(d, vocab_size) for d in doc_test]

In [22]:
encoded_doc_test

[[27, 33]]

In [23]:
padded_doc_test = pad_sequences(encoded_doc_test, maxlen=max_length, padding='post')

In [24]:
padded_doc_test

array([[27, 33,  0,  0]])

In [25]:
yhat = model.predict_classes(padded_doc_test, verbose=0)



Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [26]:
yhat

array([[1]])

In [27]:
# 1 means Positive Sentiment

In [ ]:
# OR 

In [32]:
yhat1  = model.predict(padded_doc_test)

In [33]:
yhat1

array([[0.5377396]], dtype=float32)

In [ ]:
# 0.5377 is > 0.5 hence Positive Sentiment